# Show command set

show_params = {
    "show apps": ["DisplayName", "DisplayVersion", "Publisher"],
    "show arp": ["ifIndex", "InterfaceAlias", "LinkLayerAddress", "IPAddress", "State"],
    "show bgp aggregate": [],
    "show bgp advertise": [],
    "show bgp id": [],
    "show bgp peer": [],
    "show bgp status": [],
    "show bitlocker": ["Volume", "ProtectionStatus", "LockStatus"],
    "show bootconfig": ["Path", "Description", "OSDevice", "BootDevice"],
    "show certificates": ["FriendlyName", "Issuer", "Subject", "Thumbprint"],
    "show certificates local": ["Subject", "Issuer", "Thumbprint", "NotBefore","NotAfter"],
    "show cluster status": ["Name", "State", "OwnerNode", "ResourceType"],
    "show connected devices": ["DeviceId", "Name", "Status", "Class"],
    "show cpu usage": ["ID", "Name", "CPU"],
    "show crash dumps": ["Name", "Size", "DateCreated"],
    "show datastores": ["Name", "Capacity", "FreeSpace", "Type"],
    "show dhcp leases": ["LeaseDuration", "LeaseObtainedTime", "LeaseExpiryTime", "DHCPServer"],
    "show disk": ["DriveLetter", "FileSystem", "FileSystemLabel", "DriveType", "OperationalStatus", "HealthStatus", "Size", "SizeRemaining"],
    "show disk performance": ["Disk", "Reads", "Writes", "Transfers", "IdleTime"],
    "show disk usage": ["DriveLetter", "Size", "FreeSpace"],
    "show dns cache": ["Type", "Entry", "Data", "Section", "TTL", "Status"],
    "show dns forwarders": ["IPAddress", "State", "IsRecurse", "UseRootHint"],
    "show dns records": ["HostName", "RecordType", "IPAddress", "TTL"],
    "show dns server": ["InterfaceIndex", "InterfaceAlias", "ServerAddresses"],
    "show dns zones": ["Name", "PrimaryServer", "ZoneType", "ReplicationScope"],
    "show dsc configuration": ["ResourceId", "ModuleName", "ConfigurationName"],
    "show dsc status": ["JobId", "Status", "ConfigurationName"],
    "show environment variables": ["Name", "Value"],
    "show event log": ["TimeCreated", "Id", "LevelDisplayName", "Message", "LogName"],
    "show event subscriptions": ["SubscriptionId", "Name", "Destination", "Status"],
    "show filesystem usage": ["Name", "Size", "FreeSpace"],
    "show firewall inbound rules": ["Name", "Description", "Enabled", "Direction", "Protocol", "LocalPort", "RemotePort"],
    "show firewall outbound rules": ["Name", "Description", "Enabled", "Direction", "Protocol", "LocalPort", "RemotePort"],
    "show firewall rules": ["Name", "DisplayName", "Description", "Enabled", "Direction", "Action"],
    "show fwall profile": ["Name", "DisplayName", "Description", "Enabled", "Direction", "Action"],
    "show group policy": ["GPOName", "Link", "Enabled", "Enforced"],
    "show hardware inventory": ["Name", "Manufacturer", "Model", "Status"],
    "show installed applications": ["DisplayName", "DisplayVersion", "Publisher"],
    "show installed features": ["FeatureName", "DisplayName", "Description", "InstallState"],
    "show internet options": ["Option", "Value"],
    "show ip address": ["ifIndex", "InterfaceAlias", "IPAddress", "PrefixLength", "PrefixOrigin"],
    "show ip public": ["IPAddress"],
    "show ip route": ["ifIndex", "InterfaceAlias", "Protocol", "DestinationPrefix", "NextHop", "RouteMetric", "InterfaceMetric", "Store"],
    "show ipconfig": ["IPv4Address", "SubnetMask", "DefaultGateway", "DNSServers"],
    "show ipv4 configuration": ["IPAddress", "SubnetMask", "DefaultGateway", "DNSServers"],
    "show ipv6 address": ["ifIndex", "InterfaceAlias", "IPv6Address", "PrefixLength", "PrefixOrigin"],
    "show ipv6 configuration": ["IPv6Address", "PrefixLength", "DefaultGateway", "DNSServers"],
    "show ipv6 route": ["ifIndex", "InterfaceAlias", "Protocol", "DestinationPrefix", "NextHop", "RouteMetric", "InterfaceMetric", "Store"],
    "show ipsec policies": ["PolicyName", "PolicyType", "PolicyMode"],
    "show iscsi sessions": ["SessionId", "TargetName", "InitiatorName", "Status"],
    "show kerberos tickets": ["ClientName", "ServiceName", "RenewTime"],
    "show local groups": ["Name", "Description"],
    "show local users": ["Name", "FullName", "Enabled", "LastLogonDate"],
    "show logging": ["TimeCreated", "Id", "LevelDisplayName", "Message"],
    "show logon sessions": ["LogonId", "UserName", "LogonTime"],
    "show lsi controller": ["Controller", "FirmwareVersion", "Status"],
    "show memory usage": ["TotalPhysicalMemory", "AvailablePhysicalMemory", "TotalVirtualMemory", "AvailableVirtualMemory"],
    "show msinfo": ["Component", "Description", "Value"],
    "show netsh interface ipv4": ["InterfaceAlias", "IPAddress", "SubnetMask", "DefaultGateway", "DNSServers"],
    "show netsh interface ipv6": ["InterfaceAlias", "IPv6Address", "PrefixLength", "DefaultGateway", "DNSServers"],
    "show netsh wlan show allowlisted": ["MACAddress"],
    "show netsh wlan show blocked": ["MACAddress"],
    "show netsh wlan show drivers": ["Name", "Vendor", "Provider", "Version"],
    "show netsh wlan show interfaces": ["Name", "Description", "GUID", "PhysicalAddress", "State"],
    "show netsh wlan show networks": ["SSID", "BSSID", "SignalStrength", "Channel"],
    "show netsh wlan show profiles": ["ProfileName", "SSID", "Authentication", "Encryption"],
    "show netstat": ["Protocol", "LocalAddress", "ForeignAddress", "State", "PID"],
    "show network adapters": ["Name", "MACAddress", "Status", "Speed", "IPv4Address", "IPv6Address"],
    "show network interfaces": ["InterfaceAlias", "InterfaceDescription", "Status", "MACAddress", "Speed"],
    "show nic": ["ifIndex", "InterfaceAlias", "MacAddress", "Status", "AdminStatus", "LinkSpeed", "DriverProvider", "DriverVersion"],
    "show nlb status": ["ClusterName", "NodeName", "Status"],
    "show ntp configuration": ["NTPServer", "Stratum", "LastSyncTime"],
    "show ntp status": ["Source", "Stratum", "PollInterval", "Offset"],
    "show odbc connections": ["DSNName", "Driver", "Server", "Database"],
    "show odbc drivers": ["Name", "Version", "Company"],
    "show open files": ["OpenFileID", "FileName", "AccessMode", "OpenMode"],
    "show pagefile settings": ["Name", "InitialSize", "MaximumSize"],
    "show patches": ["HotFixID", "Description", "InstalledOn"],
    "show performance counters": ["CounterSet", "CounterName", "InstanceName"],
    "show physical disks": ["DeviceId", "Manufacturer", "Model", "SerialNumber", "Size"],
    "show port scan": ["IPAddress", "Port", "Status"],
    "show power plan": ["ElementName", "InstanceID", "Name", "IsActive"],
    "show powershell version": ["PSVersion", "PSEdition", "OS", "BuildVersion"],
    "show printer jobs": ["JobId", "PrinterName", "DocumentName", "JobStatus"],
    "show printer status": ["PrinterName", "Status", "DriverName", "PortName"],
    "show printer hosts": ["Name", "PortName", "DriverName", "Shared"],
    "show process": ["Name", "CPU", "Handles", "Description"],
    "show quotas": ["UserName", "QuotaLimit", "QuotaUsed"],
    "show raid status": ["Name", "State", "VirtualDisk"],
    "show recent files": ["Name", "DateCreated", "Size"],
    "show registry values": ["Key", "ValueName", "Value"],
    "show remote desktop settings": ["Setting", "Value"],
    "show resource monitor": ["Resource", "Used", "Available"],
    "show route print": ["NetworkDestination", "Netmask", "Gateway", "Interface", "Metric"],
    "show scheduled jobs": ["JobName", "NextRunTime", "LastRunTime", "Status"],
    "show scheduled tasks": ["TaskName", "TaskPath", "State", "LastRunTime", "NextRunTime"],
    "show security log": ["TimeCreated", "Id", "LevelDisplayName", "Message"],
    "show server roles": ["Name", "InstallState"],
    "show service status": ["Name", "Status", "StartType"],
    "show services": ["Name", "DisplayName", "Status", "StartType"],
    "show shared folders": ["Name", "Path", "Description"],
    "show shutdown history": ["EventID", "TimeCreated", "Message"],
    "show smart status": ["DeviceId", "Status", "FailurePredicted"],
    "show smb connections": ["SessionId", "UserName", "ClientComputerName", "ConnectionState"],
    "show smb shares": ["Name", "Path", "Description", "Status"],
    "show software updates": ["Title", "Description", "InstalledOn"],
    "show storage pools": ["Name", "Status", "Size", "FreeSpace"],
    "show storage spaces": ["Name", "Status", "Size", "FreeSpace"],
    "show subnet information": ["SubnetId", "Network", "BroadcastAddress", "SubnetMask"],
    "show system event log": ["TimeCreated", "Id", "LevelDisplayName", "Message"],
    "show system information": ["Name", "Value"],
    "show system services": ["Name", "DisplayName", "Status", "StartType"],
    "show tcp status": ["State", "LocalAddress", "LocalPort", "RemoteAddress", "RemotePort", "OwningProcess"],
    "show tcp status detailed": ["State", "LocalAddress", "LocalPort", "RemoteAddress", "RemotePort", "OwningProcess", "CreationTime"],
    "show tcp status ipv4": ["LocalAddress", "LocalPort", "RemoteAddress", "RemotePort", "State"],
    "show tcp status ipv4 detailed": ["LocalAddress", "LocalPort", "RemoteAddress", "RemotePort", "State", "OwningProcess", "CreationTime"],
    "show tcp status ipv6": ["LocalAddress", "LocalPort", "RemoteAddress", "RemotePort", "State"],
    "show tcp status ipv6 detailed": ["LocalAddress", "LocalPort", "RemoteAddress", "RemotePort", "State", "OwningProcess", "CreationTime"],
    "show tcp global": ["SettingName", "SettingValue"],
    "show tcp provider": ["SettingName", "CongestionProvider", "MinRto", "DelayedAckTimeout", "InitialCongestionWindow", "MaxSynRetransmissions"],
    "show tcp statistics": ["ReceivedSegmentCount", "SentSegmentCount", "ResentSegmentCount", "CurrentConnections"],
    "show tcp config": ["SettingName", "MemoryPressureProtection","CongestionProvider","EcnCapability","Timestamps"],
    "show terminal services": ["Name", "State", "UserName"],
    "show top": ["Id", "Name", "CPU", "Handles", "Description"],
    "show uptime": ["Days", "Hours", "Minutes"],
    "show usb devices": ["DeviceId", "Name", "Description", "Status"],
    "show user groups": ["UserName", "GroupName"],
    "show vdi status": ["Name", "State", "HostServer"],
    "show virtualization hosts": ["Name", "Status", "Role"],
    "show virtualization settings": ["SettingName", "Value"],
    "show vm configuration": ["Name", "Path", "Status"],
    "show vm status": ["Name", "State", "Host"],
    "show vpn": ["Name", "ServerAddress", "TunnelType", "IPSecCustomPolicy", "AuthenticationMethod", "ConnectionStatus", "SplitTunneling", "RememberCredential"],
    "show vpn status": ["ConnectionStatus", "AuthenticationMethod", "EncryptionLevel", "IPAddress"],
    "show vss writers": ["WriterName", "State", "LastError"],
    "show wifi connections": ["SSID", "Authentication", "Encryption", "BSSID"],
    "show wifi networks": ["SSID", "BSSID", "SignalStrength", "Channel"],
    "show windows defender status": ["AMProductVersion", "AntispywareEnabled", "AntivirusEnabled"],
    "show windows firewall": ["Profile", "State"],
    "show windows licensing": ["LicenseStatus", "Description"],
    "show windows services": ["Name", "DisplayName", "Status", "StartType"],
    "show windows updates": ["Title", "Description", "KBArticleID", "InstalledOn"],
    "show winrm configuration": ["SettingName", "Value"],
    "show wmi objects": ["Namespace", "ClassName", "PropertyName", "Value"],
    "show wsus status": ["ComputerName", "LastStatusReport", "UpdateStatus"],
}

show_commands = {
    "show apps": f"Get-ItemProperty HKLM:\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* | Select-Object {', '.join(show_params.get('show apps'))} | ConvertTo-Json",
    "show arp": f"Get-NetNeighbor -State Reachable,Stale | Select-Object -Property {', '.join(show_params.get('show arp'))} | ConvertTo-Json",
    "show bgp aggregate": "Get-BgpRouteAggregate",
    "show bgp advertise": "Get-BgpCustomRoute",
    "show bgp id": "Get-BgpRouter | Select-Object BgpIdentifier, LocalASN, TransitRouting, RouteReflector | Format-List",
    "show bgp peer": "Get-BgpPeer -Verbose | Format-List",
    "show bgp status": "Get-BgpStatistics",
    "show bitlocker": f"Get-BitLockerVolume | Select-Object -Property {', '.join(show_params.get('show bitlocker'))} | ConvertTo-Json",
    "show bootconfig": f"Bcdedit /enum all | ConvertTo-Json",
    "show certificates": f"Get-ChildItem -Path Cert:\\LocalMachine\\My | Select-Object -Property {', '.join(show_params.get('show certificates'))} | ConvertTo-Json",
    "show certificates local": f"Get-ChildItem -Path Cert:\\LocalMachine\\My | Select-Object -Property {', '.join(show_params.get('show certificates local'))} | ConvertTo-Json",
    "show cluster status": f"Get-ClusterGroup | Select-Object -Property {', '.join(show_params.get('show cluster status'))} | ConvertTo-Json",
    "show connected devices": f"Get-PnpDevice | Select-Object -Property {', '.join(show_params.get('show connected devices'))} | ConvertTo-Json",
    "show cpu usage": f"Get-Process | Select-Object -Property {', '.join(show_params.get('show cpu usage'))} | ConvertTo-Json",
    "show crash dumps": f"Get-ChildItem -Path C:\\Windows\\Minidump\\*.dmp | Select-Object -Property {', '.join(show_params.get('show crash dumps'))} | ConvertTo-Json",
    "show datastores": f"Get-Datastore | Select-Object -Property {', '.join(show_params.get('show datastores'))} | ConvertTo-Json",
    "show dhcp leases": f"Get-DhcpServerv4Lease | Select-Object -Property {', '.join(show_params.get('show dhcp leases'))} | ConvertTo-Json",
    "show disk": f"Get-Volume | Select-Object -Property {', '.join(show_params.get('show disk'))} | ConvertTo-Json",
    "show disk performance": f"Get-DiskPerformance | Select-Object -Property {', '.join(show_params.get('show disk performance'))} | ConvertTo-Json",
    "show disk usage": f"Get-PSDrive -PSProvider FileSystem | Select-Object -Property {', '.join(show_params.get('show disk usage'))} | ConvertTo-Json",
    "show dns cache": f"Get-DnsClientCache | Select-Object -Property {', '.join(show_params.get('show dns cache'))} | ConvertTo-Json",
    "show dns forwarders": f"Get-DnsServerForwarder | Select-Object -Property {', '.join(show_params.get('show dns forwarders'))} | ConvertTo-Json",
    "show dns records": f"Get-DnsServerResourceRecord | Select-Object -Property {', '.join(show_params.get('show dns records'))} | ConvertTo-Json",
    "show dns server": f"Get-DnsClientServerAddress | Sort-Object -Property {', '.join(show_params.get('show dns server'))} | ConvertTo-Json",
    "show dns zones": f"Get-DnsServerZone | Select-Object -Property {', '.join(show_params.get('show dns zones'))} | ConvertTo-Json",
    "show dsc configuration": f"Get-DscConfiguration | Select-Object -Property {', '.join(show_params.get('show dsc configuration'))} | ConvertTo-Json",
    "show dsc status": f"Get-DscLocalConfigurationManager | Select-Object -Property {', '.join(show_params.get('show dsc status'))} | ConvertTo-Json",
    "show environment variables": f"Get-ChildItem Env: | Select-Object -Property {', '.join(show_params.get('show environment variables'))} | ConvertTo-Json",
    "show event log": f"Get-WinEvent -LogName System, Application -MaxEvents 100 | Select-Object -Property {', '.join(show_params.get('show event log'))} | ConvertTo-Json",
    "show event subscriptions": f"Get-WinEvent -ListLog * | Select-Object -Property {', '.join(show_params.get('show event subscriptions'))} | ConvertTo-Json",
    "show filesystem usage": f"Get-PSDrive -PSProvider FileSystem | Select-Object -Property {', '.join(show_params.get('show filesystem usage'))} | ConvertTo-Json",
    "show firewall inbound rules": f"Get-NetFirewallRule -Direction Inbound | Select-Object -Property {', '.join(show_params.get('show firewall inbound rules'))} | ConvertTo-Json",
    "show firewall outbound rules": f"Get-NetFirewallRule -Direction Outbound | Select-Object -Property {', '.join(show_params.get('show firewall outbound rules'))} | ConvertTo-Json",
    "show firewall rules": f"Get-NetFirewallRule | Select-Object -Property {', '.join(show_params.get('show firewall rules'))} | ConvertTo-Json",
    "show fwall profile": f"Get-NetFirewallProfile | Select-Object -Property {', '.join(show_params.get('show fwall profile'))} | ConvertTo-Json",
    "show group policy": f"Get-GPResultantSetOfPolicy -ReportType HTML | ConvertTo-Json",
    "show hardware inventory": f"Get-WmiObject -Class Win32_ComputerSystem | Select-Object -Property {', '.join(show_params.get('show hardware inventory'))} | ConvertTo-Json",
    "show installed applications": f"Get-ItemProperty HKLM:\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* | Select-Object -Property {', '.join(show_params.get('show installed applications'))} | ConvertTo-Json",
    "show installed features": f"Get-WindowsFeature | Select-Object -Property {', '.join(show_params.get('show installed features'))} | ConvertTo-Json",
    "show internet options": f"Get-InternetOption | ConvertTo-Json",
    "show ip address": f"Get-NetIPAddress -AddressFamily IPv4 | Select-Object -Property {', '.join(show_params.get('show ip address'))} | ConvertTo-Json",
    "show ip public": "Invoke-RestMethod -Uri \"http://ipinfo.io/ip\"",
    "show ip route": f"Get-NetRoute -AddressFamily ipv4 | Sort-Object -Property {', '.join(show_params.get('show ip route'))} | ConvertTo-Json",
    "show ipconfig": f"Get-NetIPAddress | Select-Object -Property {', '.join(show_params.get('show ipconfig'))} | ConvertTo-Json",
    "show ipv4 configuration": f"Get-NetIPAddress -AddressFamily IPv4 | Select-Object -Property {', '.join(show_params.get('show ipv4 configuration'))} | ConvertTo-Json",
    "show ipv6 address": f"Get-NetIPAddress -AddressFamily IPv6 | Select-Object -Property {', '.join(show_params.get('show ipv6 address'))} | ConvertTo-Json",
    "show ipv6 configuration": f"Get-NetIPAddress -AddressFamily IPv6 | Select-Object -Property {', '.join(show_params.get('show ipv6 configuration'))} | ConvertTo-Json",
    "show ipv6 route": f"Get-NetRoute -AddressFamily ipv6 | Sort-Object -Property {', '.join(show_params.get('show ipv6 route'))} | ConvertTo-Json",
    "show ipsec policies": f"Get-NetIPsecPolicy | Select-Object -Property {', '.join(show_params.get('show ipsec policies'))} | ConvertTo-Json",
    "show iscsi sessions": f"Get-IscsiSession | Select-Object -Property {', '.join(show_params.get('show iscsi sessions'))} | ConvertTo-Json",
    "show kerberos tickets": f"klist | ConvertTo-Json",
    "show local groups": f"Get-LocalGroup | Select-Object -Property {', '.join(show_params.get('show local groups'))} | ConvertTo-Json",
    "show local users": f"Get-LocalUser | Select-Object -Property {', '.join(show_params.get('show local users'))} | ConvertTo-Json",
    "show logging": f"Get-WinEvent -LogName System, Application -MaxEvents 1000 | Select-Object -Property {', '.join(show_params.get('show logging'))} | Format-Table -AutoSize -HideTableHeaders | Out-String",
    "show logon sessions": f"Get-LogonSession | Select-Object -Property {', '.join(show_params.get('show logon sessions'))} | ConvertTo-Json",
    "show lsi controller": f"Get-LSIController | Select-Object -Property {', '.join(show_params.get('show lsi controller'))} | ConvertTo-Json",
    "show memory usage": f"Get-Process | Select-Object -Property {', '.join(show_params.get('show memory usage'))} | ConvertTo-Json",
    "show msinfo": f"Get-WmiObject -Class Win32_OperatingSystem | Select-Object -Property {', '.join(show_params.get('show msinfo'))} | ConvertTo-Json",
    "show netsh interface ipv4": f"Get-NetIPConfiguration | Select-Object -Property {', '.join(show_params.get('show netsh interface ipv4'))} | ConvertTo-Json",
    "show netsh interface ipv6": f"Get-NetIPConfiguration -AddressFamily IPv6 | Select-Object -Property {', '.join(show_params.get('show netsh interface ipv6'))} | ConvertTo-Json",
    "show netsh wlan show allowlisted": f"netsh wlan show allowlisted | Select-Object -Property {', '.join(show_params.get('show netsh wlan show allowlisted'))} | ConvertTo-Json",
    "show netsh wlan show blocked": f"netsh wlan show blocked | Select-Object -Property {', '.join(show_params.get('show netsh wlan show blocked'))} | ConvertTo-Json",
    "show netsh wlan show drivers": f"netsh wlan show drivers | Select-Object -Property {', '.join(show_params.get('show netsh wlan show drivers'))} | ConvertTo-Json",
    "show netsh wlan show interfaces": f"netsh wlan show interfaces | Select-Object -Property {', '.join(show_params.get('show netsh wlan show interfaces'))} | ConvertTo-Json",
    "show netsh wlan show networks": f"netsh wlan show networks | Select-Object -Property {', '.join(show_params.get('show netsh wlan show networks'))} | ConvertTo-Json",
    "show netsh wlan show profiles": f"netsh wlan show profiles | Select-Object -Property {', '.join(show_params.get('show netsh wlan show profiles'))} | ConvertTo-Json",
    "show netstat": f"Get-NetTCPConnection | Select-Object -Property {', '.join(show_params.get('show netstat'))} | ConvertTo-Json",
    "show network adapters": f"Get-NetAdapter | Select-Object -Property {', '.join(show_params.get('show network adapters'))} | ConvertTo-Json",
    "show network interfaces": f"Get-NetAdapter | Select-Object -Property {', '.join(show_params.get('show network interfaces'))} | ConvertTo-Json",
    "show nic": f"Get-NetAdapter | Select-Object -Property {', '.join(show_params.get('show nic'))} | ConvertTo-Json",
    "show nlb status": f"Get-NLBClusterNode | Select-Object -Property {', '.join(show_params.get('show nlb status'))} | ConvertTo-Json",
    "show ntp configuration": f"w32tm /query /configuration | ConvertTo-Json",
    "show ntp status": f"w32tm /query /status | ConvertTo-Json",
    "show odbc connections": f"Get-OdbcDsn | Select-Object -Property {', '.join(show_params.get('show odbc connections'))} | ConvertTo-Json",
    "show odbc drivers": f"Get-OdbcDriver | Select-Object -Property {', '.join(show_params.get('show odbc drivers'))} | ConvertTo-Json",
    "show open files": f"Get-OpenFile | Select-Object -Property {', '.join(show_params.get('show open files'))} | ConvertTo-Json",
    "show pagefile settings": f"Get-PageFile | Select-Object -Property {', '.join(show_params.get('show pagefile settings'))} | ConvertTo-Json",
    "show patches": f"Get-HotFix | Select-Object -Property {', '.join(show_params.get('show patches'))} | ConvertTo-Json",
    "show performance counters": f"Get-Counter -ListSet * | Select-Object -Property {', '.join(show_params.get('show performance counters'))} | ConvertTo-Json",
    "show physical disks": f"Get-PhysicalDisk | Select-Object -Property {', '.join(show_params.get('show physical disks'))} | ConvertTo-Json",
    "show port scan": f"Test-NetConnection -Port 80 | ConvertTo-Json",
    "show power plan": f"Get-WmiObject -Namespace root\\cimv2\\power -Class Win32_PowerPlan | Select-Object -Property {', '.join(show_params.get('show power plan'))} | ConvertTo-Json",
    "show powershell version": "[pscustomobject]@{ PSVersion = $PSVersionTable.PSVersion; PSEdition = $PSVersionTable.PSEdition; OS = $PSVersionTable.OS; BuildVersion = $PSVersionTable.BuildVersion } | ConvertTo-Json",
    "show printer jobs": f"Get-PrintJob | Select-Object -Property {', '.join(show_params.get('show printer jobs'))} | ConvertTo-Json",
    "show printer status": f"Get-Printer | Select-Object -Property {', '.join(show_params.get('show printer status'))} | ConvertTo-Json",
    "show printer hosts": f"Get-Printer | Select-Object -Property {', '.join(show_params.get('show printer hosts'))} | ConvertTo-Json",
    "show process": f"Get-Process | Select-Object -Property {', '.join(show_params.get('show process'))} | Sort-Object -Property CPU -Descending | ConvertTo-Json",
    "show quotas": f"Get-FsrmQuota | Select-Object -Property {', '.join(show_params.get('show quotas'))} | ConvertTo-Json",
    "show raid status": f"Get-RaidStatus | Select-Object -Property {', '.join(show_params.get('show raid status'))} | ConvertTo-Json",
    "show recent files": f"Get-ChildItem -Path C:\\ | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 10 -Property {', '.join(show_params.get('show recent files'))} | ConvertTo-Json",
    "show registry values": f"Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' | Select-Object -Property {', '.join(show_params.get('show registry values'))} | ConvertTo-Json",
    "show remote desktop settings": f"Get-RDUserSession | Select-Object -Property {', '.join(show_params.get('show remote desktop settings'))} | ConvertTo-Json",
    "show resource monitor": f"Get-ResourceMonitor | Select-Object -Property {', '.join(show_params.get('show resource monitor'))} | ConvertTo-Json",
    "show route print": f"route print | Select-Object -Property {', '.join(show_params.get('show route print'))} | ConvertTo-Json",
    "show scheduled jobs": f"Get-ScheduledJob | Select-Object -Property {', '.join(show_params.get('show scheduled jobs'))} | ConvertTo-Json",
    "show scheduled tasks": f"Get-ScheduledTask | Select-Object -Property {', '.join(show_params.get('show scheduled tasks'))} | ConvertTo-Json",
    "show security log": f"Get-WinEvent -LogName Security | Select-Object -Property {', '.join(show_params.get('show security log'))} | ConvertTo-Json",
    "show server roles": f"Get-WindowsFeature | Select-Object -Property {', '.join(show_params.get('show server roles'))} | ConvertTo-Json",
    "show service status": f"Get-Service | Select-Object -Property {', '.join(show_params.get('show service status'))} | ConvertTo-Json",
    "show services": f"Get-Service | Select-Object -Property {', '.join(show_params.get('show services'))} | ConvertTo-Json",
    "show shared folders": f"Get-SmbShare | Select-Object -Property {', '.join(show_params.get('show shared folders'))} | ConvertTo-Json",
    "show shutdown history": f"Get-WinEvent -LogName System -FilterXPath '*[System[EventID=1074]]' | Select-Object -Property {', '.join(show_params.get('show shutdown history'))} | ConvertTo-Json",
    "show smart status": f"Get-PhysicalDisk | Select-Object -Property {', '.join(show_params.get('show smart status'))} | ConvertTo-Json",
    "show smb connections": f"Get-SmbConnection | Select-Object -Property {', '.join(show_params.get('show smb connections'))} | ConvertTo-Json",
    "show smb shares": f"Get-SmbShare | Select-Object -Property {', '.join(show_params.get('show smb shares'))} | ConvertTo-Json",
    "show software updates": f"Get-WindowsUpdate | Select-Object -Property {', '.join(show_params.get('show software updates'))} | ConvertTo-Json",
    "show storage pools": f"Get-StoragePool | Select-Object -Property {', '.join(show_params.get('show storage pools'))} | ConvertTo-Json",
    "show storage spaces": f"Get-StorageSpace | Select-Object -Property {', '.join(show_params.get('show storage spaces'))} | ConvertTo-Json",
    "show subnet information": f"Get-Subnet | Select-Object -Property {', '.join(show_params.get('show subnet information'))} | ConvertTo-Json",
    "show system event log": f"Get-WinEvent -LogName System | Select-Object -Property {', '.join(show_params.get('show system event log'))} | ConvertTo-Json",
    "show system information": f"Get-ComputerInfo | Select-Object -Property {', '.join(show_params.get('show system information'))} | ConvertTo-Json",
    "show system services": f"Get-Service | Select-Object -Property {', '.join(show_params.get('show system services'))} | ConvertTo-Json",
    "show tcp status": f"Get-NetTCPConnection | Select-Object -Property {', '.join(show_params.get('show tcp status'))} | ConvertTo-Json",
    "show tcp status detailed": f"Get-NetTCPConnection | Select-Object -Property {', '.join(show_params.get('show tcp status detailed'))} | ConvertTo-Json",
    "show tcp status ipv4": f"Get-NetTCPConnection -AddressFamily IPv4 | Select-Object -Property {', '.join(show_params.get('show tcp status ipv4'))} | ConvertTo-Json",
    "show tcp status ipv4 detailed": f"Get-NetTCPConnection -AddressFamily IPv4 | Select-Object -Property {', '.join(show_params.get('show tcp status ipv4 detailed'))} | ConvertTo-Json",
    "show tcp status ipv6": f"Get-NetTCPConnection -AddressFamily IPv6 | Select-Object -Property {', '.join(show_params.get('show tcp status ipv6'))} | ConvertTo-Json",
    "show tcp status ipv6 detailed": f"Get-NetTCPConnection -AddressFamily IPv6 | Select-Object -Property {', '.join(show_params.get('show tcp status ipv6 detailed'))} | ConvertTo-Json",
    "show tcp global": f"Get-NetTCPSetting -SettingName \"global\" | Select-Object -Property {', '.join(show_params.get('show tcp global'))} | ConvertTo-Json",
    "show tcp provider": f"Get-NetTCPSetting | Select-Object -Property {', '.join(show_params.get('show tcp provider'))} | Format-Table -AutoSize",
    "show tcp statistics": f"Get-NetTCPSetting | Select-Object -Property {', '.join(show_params.get('show tcp statistics'))} | ConvertTo-Json",
    "show tcp status": f"Get-NetTCPConnection | Select-Object -Property {', '.join(show_params.get('show tcp status'))} | ConvertTo-Json",
    "show tcp config": f"Get-NetIPConfiguration | Select-Object -Property {', '.join(show_params.get('show tcp config'))} | ConvertTo-Json",
    "show terminal services": f"Get-TerminalService | Select-Object -Property {', '.join(show_params.get('show terminal services'))} | ConvertTo-Json",
    "show top": f"Get-Process | Sort-Object CPU -Descending | Select-Object -First 10 -Property {', '.join(show_params.get('show top'))} | ConvertTo-Json",
    "show uptime": f"Get-Uptime | ConvertTo-Json",
    "show usb devices": f"Get-PnpDevice -Class 'USB' | Select-Object -Property {', '.join(show_params.get('show usb devices'))} | ConvertTo-Json",
    "show user groups": f"Get-LocalGroupMember | Select-Object -Property {', '.join(show_params.get('show user groups'))} | ConvertTo-Json",
    "show vdi status": f"Get-VdiStatus | Select-Object -Property {', '.join(show_params.get('show vdi status'))} | ConvertTo-Json",
    "show virtualization hosts": f"Get-VMHost | Select-Object -Property {', '.join(show_params.get('show virtualization hosts'))} | ConvertTo-Json",
    "show virtualization settings": f"Get-VMHostSetting | Select-Object -Property {', '.join(show_params.get('show virtualization settings'))} | ConvertTo-Json",
    "show vm configuration": f"Get-VM | Select-Object -Property {', '.join(show_params.get('show vm configuration'))} | ConvertTo-Json",
    "show vm status": f"Get-VM | Select-Object -Property {', '.join(show_params.get('show vm status'))} | ConvertTo-Json",
    "show vpn": f"Get-VpnConnection | Select-Object -Property {', '.join(show_params.get('show vpn'))} | ConvertTo-Json",
    "show vpn status": f"Get-VpnConnection | Select-Object -Property {', '.join(show_params.get('show vpn status'))} | ConvertTo-Json",
    "show vss writers": f"Get-VSSWriter | Select-Object -Property {', '.join(show_params.get('show vss writers'))} | ConvertTo-Json",
    "show wifi connections": f"Get-NetAdapter | Select-Object -Property {', '.join(show_params.get('show wifi connections'))} | ConvertTo-Json",
    "show wifi networks": f"Get-NetAdapterStatistics | Select-Object -Property {', '.join(show_params.get('show wifi networks'))} | ConvertTo-Json",
    "show windows defender status": f"Get-MpComputerStatus | Select-Object -Property {', '.join(show_params.get('show windows defender status'))} | ConvertTo-Json",
    "show windows firewall": f"Get-NetFirewallProfile | Select-Object -Property {', '.join(show_params.get('show windows firewall'))} | ConvertTo-Json",
    "show windows licensing": f"Get-WmiObject -Class SoftwareLicensingService | Select-Object -Property {', '.join(show_params.get('show windows licensing'))} | ConvertTo-Json",
    "show windows services": f"Get-Service | Select-Object -Property {', '.join(show_params.get('show windows services'))} | ConvertTo-Json",
    "show windows updates": f"Get-WindowsUpdate | Select-Object -Property {', '.join(show_params.get('show windows updates'))} | ConvertTo-Json",
    "show winrm configuration": f"Get-WSManInstance -ResourceURI winrm/config | Select-Object -Property {', '.join(show_params.get('show winrm configuration'))} | ConvertTo-Json",
    "show wmi objects": f"Get-WmiObject -Namespace root\\cimv2 -Class Win32_LogicalDisk | Select-Object -Property {', '.join(show_params.get('show wmi objects'))} | ConvertTo-Json",
    "show wsus status": f"Get-WsusServerStatus | Select-Object -Property {', '.join(show_params.get('show wsus status'))} | ConvertTo-Json",
    "notfound": "notfound"
}
