# Show command set

show_params = {
    "show arp": ["ifIndex", "InterfaceAlias", "LinkLayerAddress", "IPAddress", "State"],
    "show dns cache":["Type", "Entry", "Data", "Section", "TTL", "Status"],
    "show dns server":["InterfaceIndex","InterfaceAlias","ServerAddresses"],
    "show logging":["TimeCreated", "Id", "LevelDisplayName", "Message"],
    "show nic": ["ifIndex", "InterfaceAlias", "MacAddress", "Status", "AdminStatus", "LinkSpeed", "DriverProvider", "DriverVersion"],
    "show ip address":["ifIndex","InterfaceAlias","IPAddress","PrefixLength","PrefixOrigin"],
    "show process":["Name","CPU","Handles","VM","WS","Description"],
    "show ip public":["\@{Name='Your IP:';Expression={$_.Content}}"],
    "show vpn":["Name","ServerAddress","TunnelType","IPSecCustomPolicy","AuthenticationMethod","ConnectionStatus","SplitTunneling","RememberCredential"],
    "show ipv6 address":["ifIndex","InterfaceAlias","IPv6Address","PrefixLength","PrefixOrigin"],
    "show disk":["DriveLetter","FileSystem","FileSystemLabel","DriveType","OperationalStatus", "HealthStatus","Size","SizeRemaining"],
    "show ip route":["ifIndex", "InterfaceAlias","Protocol","DestinationPrefix","NextHop","RouteMetric","InterfaceMetric","Store"],
    "show ipv6 route":["ifIndex", "InterfaceAlias","Protocol","DestinationPrefix","NextHop","RouteMetric","InterfaceMetric","Store"],
}

show_commands = {
    "show arp":f"Get-NetNeighbor -State Reachable,Stale | Select-Object -Property {", ".join(show_params.get("show arp"))} | ConvertTo-Json",
    "show bgp aggregate":"Get-BgpRouteAggregate",
    "show bgp advertise":"Get-BgpCustomRoute",
    "show bgp id":"Get-BgpRouter | Select-Object BgpIdentifier, LocalASN, TransitRouting, RouteReflector | Format-List",
    "show bgp peer":"Get-BgpPeer -Verbose | Format-List",
    "show bgp status":"Get-BgpStatistics",
    "show dns cache":f"Get-DnsClientCache | Select-Object -Property {", ".join(show_params.get("show dns cache"))} | ConvertTo-Json",
    "show dns server":f"Get-DnsClientServerAddress | Sort-Object -Property {", ".join(show_params.get("show dns server"))} | ConvertTo-Json",
    "show disk":f"Get-Volume | Select-Object -Property {", ".join(show_params.get("show disk"))} | ConvertTo-Json",
    "show fwall profile":"Get-NetFirewallProfile",
    "show gpo":"gpresult /R",
    "show nic":f"Get-NetAdapter | Select-Object -Property {", ".join(show_params.get("show nic"))} | ConvertTo-Json",
    "show ip address":f"Get-NetIPAddress -AddressFamily IPv4 | Select-Object -Property {", ".join(show_params.get("show ip address"))} | ConvertTo-Json",
    "show ip public":f"Invoke-WebRequest https://itomation.ca/mypublicip | Select-Object {", ".join(show_params.get("show ip public"))} | ConvertTo-Json",
    "show ip route":f"Get-NetRoute -AddressFamily ipv4 | Sort-Object -Property {", ".join(show_params.get("show ip route"))} | ConvertTo-Json",
    "show ipv6 address":f"Get-NetIPAddress -AddressFamily IPv6 | Select-Object -Property {", ".join(show_params.get("show ipv6 address"))} | ConvertTo-Json",
    "show ipv6 public":"(Invoke-WebRequest ip6only.me/api/).content",
    "show ipv6 route":f"Get-NetRoute -AddressFamily ipv6 | Sort-Object -Property {", ".join(show_params.get("show ipv6 route"))} | ConvertTo-Json",
    "show logging":f"Get-WinEvent -LogName System, Application -MaxEvents 1000 | Select-Object -Property {", ".join(show_params.get("show logging"))} | Format-Table -AutoSize -HideTableHeaders | Out-String",
    "show powershell version":"[pscustomobject]@{ PSVersion = $PSVersionTable.PSVersion; PSEdition = $PSVersionTable.PSEdition; OS = $PSVersionTable.OS; BuildVersion = $PSVersionTable.BuildVersion } | ConvertTo-Json",
    "show top":"Get-Process | Sort-Object -Property WS | Select-Object -Last 10 | sort-object -Property CPU -Descending",
    "show process":f"Get-Process | Select-Object -Property {", ".join(show_params.get("show process"))} | Sort-Object -Property CPU -Descending | ConvertTo-Json",
    "show programs":r"Get-ItemProperty HKLM:\\Software\\Wow6432Node\\Microsoft\Windows\\CurrentVersion\\Uninstall\\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize",
    "show svc":"Get-Service | Sort-Object -Property Status -Descending | Format-Table -AutoSize",
    "show tcp":"netstat -n",
    "show vpn":f"Get-VpnConnection | Select-Object -Property {", ".join(show_params.get("show vpn"))} | ConvertTo-Json",
    "notfound":"notfound",
}
